Controllers/HatsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hatshop.Data;
using hatshop.Models;
using hatshop.ViewModels;

namespace hatshop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HatsController : Controller
    {
        private readonly HatShopDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public HatsController(HatShopDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Hats
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hats.Include(h => h.Category).ToListAsync());
        }

        // GET: Hats/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hat = await _context.Hats.Include(h => h.Category)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (hat == null)
            {
                return NotFound();
            }

            ViewData["Picture"] = String.IsNullOrEmpty(hat.PicturePath) ? "default.png" : hat.PicturePath;
            return View(hat);
        }

        // GET: Hats/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", null);
            ViewData["Picture"] = "default.png";
            return View();
        }

        // POST: Hats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HatPictureViewModel hatPictureViewModel)
        {
            if (ModelState.IsValid)
            {
                hatPictureViewModel.Hat.PicturePath = String.IsNullOrEmpty(hatPictureViewModel.Hat.PicturePath)
                ? UploadedFile(hatPictureViewModel, null)
                : "default.png";

                _context.Add(hatPictureViewModel.Hat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Picture"] = "default.png";
            return View(hatPictureViewModel);
        }

        // GET: Hats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hat = await _context.Hats.FindAsync(id);

            if (hat == null)
            {
                return NotFound();
            }

            HatPictureViewModel hatPictureViewModel = new HatPictureViewModel
            {
                Hat = hat
            };

            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", null);
            ViewData["Picture"] = String.IsNullOrEmpty(hat.PicturePath) ? "default.png" : hat.PicturePath;
            return View(hatPictureViewModel);
        }

        // POST: Hats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, HatPictureViewModel hatPictureViewModel)
        {
            if (id != hatPictureViewModel.Hat.Id)
            {
                return NotFound();
            }

            var path = await _context.Hats.Where(h => h.Id == id).Select(h => h.PicturePath).FirstOrDefaultAsync();

            if (ModelState.IsValid)
            {
                try
                {
                    hatPictureViewModel.Hat.PicturePath = String.IsNullOrEmpty(hatPictureViewModel.Hat.PicturePath)
                    ? UploadedFile(hatPictureViewModel, path)
                    : path;

                    _context.Update(hatPictureViewModel.Hat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HatExists(hatPictureViewModel.Hat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["Picture"] = "default.png";
            return View(hatPictureViewModel);
        }

        // GET: Hats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hat = await _context.Hats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hat == null)
            {
                return NotFound();
            }

            return View(hat);
        }

        // POST: Hats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hat = await _context.Hats.FindAsync(id);
            _context.Hats.Remove(hat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HatExists(int id)
        {
            return _context.Hats.Any(e => e.Id == id);
        }

        private string UploadedFile(HatPictureViewModel model, string oldPath)
        {
            string uniqueFileName = null;

            if (model.Picture != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.Picture.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Picture.CopyTo(fileStream);
                }
                if (oldPath != null && oldPath != "default.png")
                    System.IO.File.Delete(Path.Combine(uploadsFolder, oldPath));
            }
            return uniqueFileName;
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hatshop.Data;
using hatshop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;

namespace hatshop.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly HatShopDbContext _context;

        public OrdersController(HatShopDbContext context)
        {
            _context = context;
        }

        public string GetUserId()
        {
            string userIdValue = User.Identity.Name;
            if (User.Identity is ClaimsIdentity claimsIdentity)
            {
                var userIdClaim = claimsIdentity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                    return userIdClaim.Value;
            }
            return string.Empty;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var userId = GetUserId();
            var orders = _context.Orders.Include(o => o.Hats).ThenInclude(h => h.Hat).Include(o => o.User).AsQueryable();
            if (!User.IsInRole("Admin"))
                orders = orders.Where(o => o.UserId == userId);

            return View(await orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            string userId = GetUserId();
            var order = await _context.Orders.Include(o => o.Hats).ThenInclude(h => h.Hat).Where(o => o.Id == id).FirstOrDefaultAsync();

            if (order == null)
            {
                return NotFound();
            }

            if (order.UserId != userId)
            {
                return Redirect("/Identity/Account/AccessDenied");
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            string userIdValue = GetUserId();
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DateTime")] Order order)
        {
            if (ModelState.IsValid)
            {
                string userIdValue = GetUserId();
                order.UserId = userIdValue;
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "FullName", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [NonAction]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,DateTime")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hatshop.Data;
using hatshop.Models;

namespace hatshop.Controllers
{
    public class ShopController : Controller
    {
        private readonly HatShopDbContext _context;

        public ShopController(HatShopDbContext context)
        {
            _context = context;
        }

        // GET: Hats
        public IActionResult Index(int? page, string filter, int? categoryId)
        {
            var allHats = _context.Hats.Include(h => h.Category).AsQueryable();
            allHats = !String.IsNullOrEmpty(filter) ? allHats.Where(h => h.Name.Contains(filter)) : allHats;
            allHats = categoryId != null ? allHats.Where(h => h.CategoryId == categoryId) : allHats;
            var hatsPage = allHats.OrderBy(h => h.Name).Skip((page - 1 ?? 0) * 6).Take(6);
            
            ViewData["NumberOfHats"] = allHats.Count();
            ViewData["Categories"] = _context.Categories;
            return View(hatsPage);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - hatshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="icon" href="~/images/icon.png" type="image/x-icon" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <link rel="stylesheet" href="~/mdb/css/mdb.min.css" />
    <link rel="stylesheet" href="~/css/site.css">
</head>

<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white" id="main-navbar">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                    data-mdb-target="#navbarExample01" aria-controls="navbarExample01" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarExample01">
                    <a class="navbar-brand" href="/">
                        <img src="~/images/icon.png" height="30" alt="" loading="lazy" />
                    </a>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Hats" asp-action="Index">Hats</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav d-flex flex-row">
                        @* Icons *@
                        <li class="nav-item me-3 me-lg-0 dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="cart-dropdown-toggle" role="button"
                                data-mdb-toggle="dropdown" aria-expanded="false">
                                <span class="badge badge-pill bg-danger no-cart-items">0</span>
                                <span><i class="fas fa-shopping-cart"></i></span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown"
                                id="cart-dropdown-menu">
                                @* Cart dropdown menu *@
                                <li id="cart-summary">
                                    <div class="card mb-3" style="width: 20rem;">
                                        <div class="card-body">
                                            <h5 class="card-title cart-hat-title">Your order</h5>
                                            <p class="card-text">
                                                You have <span class="no-cart-items">0</span> items in your cart.
                                            </p>
                                        </div>
                                        <div class="card-body">
                                            <span class="text-muted">Order total: </span>
                                            <h6 class="card-text cart-total">$0</h6>
                                            @* <button class="btn btn-danger remove-from-cart">Remove</button> *@
                                        </div>
                                        <div class="card-body d-flex flex-row" style="margin: auto;">
                                            <a href="@(User.Identity.IsAuthenticated ? "/Orders/Create" : "/Identity/Account/Login")"
                                                class="btn btn-primary card-link btn-thinner checkout-cart">Checkout</a>
                                            <a href="#" class="btn btn-danger card-link btn-thinner clear-cart">Clear
                                                cart</a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item me-3 me-lg-0" style="width: 56px;">
                                <a class="nav-link dropdown-toggle" href="#" id="user-dropdown-toggle" role="button"
                                data-mdb-toggle="dropdown" aria-expanded="false">
                                    <span><i class="fas fa-user"></i></span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown"
                                id="user-dropdown-menu">
                                    @* User dropdown menu *@
                                    <div class="card" id="user-menu-body">
                                        <div class="card-header text-muted">Account</div>
                                        <ul class="list-group list-group-flush">
                                            <a href="/Identity/Account/Manage">
                                                <li class="list-group-item">Manage account</li>
                                            </a>
                                            <a asp-controller="Orders" asp-action="Index">
                                                <li class="list-group-item">My orders</li>
                                            </a>
                                        </ul>
                                    </div>
                                </ul>
                            </li>
                            <form method="post" asp-area="Identity" asp-page="/Account/Logout">
                                <li class="nav-item me-3 me-lg-0">
                                    <a class="nav-link">
                                        <button type="submit" id="logout-btn">Logout</button>
                                    </a>
                                </li>
                            </form>
                        }
                        else
                        {
                            <li class="nav-item me-3 me-lg-0">
                                <a class="nav-link" href="/Identity/Account/Login">
                                    Login
                                </a>
                            </li>
                            <li class="nav-item me-3 me-lg-0">
                                <a class="nav-link" href="/Identity/Account/Register">
                                    Register
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/mdb/js/mdb.min.js"></script>
    <script type="text/javascript" src="~/js/createCartEntry.js"></script>
    <script type="text/javascript" src="~/js/manageCart.js"></script>
    <script type="text/javascript" src="~/js/addToCart.js"></script>
    <script type="text/javascript" src="~/js/clearCart.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var urlParams = new URLSearchParams(window.location.search);
            let pageNumber = urlParams.get('page') ?? "1";
            $(".page-link:contains('" + pageNumber + "')").css("background-color", "rgba(30, 139, 195, 0.5)");
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>